ALTER TABLE board CHANGE reg_date created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE board CHANGE upd_date updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE board
MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;